"""Inicializando

Revision ID: 113146498352
Revises: 
Create Date: 2021-09-20 10:07:04.463778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '113146498352'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('alimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alimento', sa.String(length=40), nullable=True),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alimento'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alimento')
    op.drop_table('tipo')
    # ### end Alembic commands ###
