"""Adicao tabela user

Revision ID: 44abba399da4
Revises: cd9f6174b17d
Create Date: 2021-09-22 09:08:16.515908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44abba399da4'
down_revision = 'cd9f6174b17d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=140), nullable=False),
    sa.Column('fullname', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('id', name=op.f('uq_user_id')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
