"""Tipo e alimento não pode ser vazio

Revision ID: cd9f6174b17d
Revises: 8fc423e307ec
Create Date: 2021-09-21 09:36:02.453277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd9f6174b17d'
down_revision = '8fc423e307ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alimento', schema=None) as batch_op:
        batch_op.alter_column('alimento',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)

    with op.batch_alter_table('tipo', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('alimento', schema=None) as batch_op:
        batch_op.alter_column('alimento',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)

    # ### end Alembic commands ###
