"""adicionando coluna a ser removida

Revision ID: e3f6c652c7a5
Revises: c8d68d19aa0f
Create Date: 2021-09-20 10:41:14.807908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f6c652c7a5'
down_revision = 'c8d68d19aa0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alimento', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_alimento_alimento'), ['alimento'])
        batch_op.create_unique_constraint(batch_op.f('uq_alimento_id'), ['id'])

    with op.batch_alter_table('tipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remove', sa.String(length=20), nullable=True))
        batch_op.drop_constraint('foo', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_tipo_id'), ['id'])
        batch_op.create_unique_constraint(batch_op.f('uq_tipo_tipo'), ['tipo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_tipo_tipo'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_tipo_id'), type_='unique')
        batch_op.create_unique_constraint('foo', ['tipo'])
        batch_op.drop_column('remove')

    with op.batch_alter_table('alimento', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_alimento_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_alimento_alimento'), type_='unique')

    # ### end Alembic commands ###
